spring:
  jpa:
    show-sql: true
    properties:
      hibernate.hbm2ddl.auto: update
  datasource:
    master:
      username: diyfintech
      driver-class-name: com.mysql.jdbc.Driver
      password: 163.com
      url: jdbc:mysql://192.168.0.200:3306/testdb?useUnicode=true&characterEncoding=utf-8
    slave:
      username: root
      driver-class-name: com.mysql.jdbc.Driver
      password:
      url: jdbc:mysql://localhost:3306/testdb?useUnicode=true&characterEncoding=utf-8